a=int(input("enter your first number:"))
b=int(input("enter your second number:"))
print("addition of given two number is",a+b)
print("subraction of given two number is",a-b)
print("multiplication of given two number is",a*b)
print("division of given two number is",a/b)
print("floor divion of given two number is",a//b)
print("modulus of given two number is",a%b)
